### PR TITLE
Update to 0.47.0

### LINKED ISSUE #12: Obsolete runtime?
Hello,
When installing the package from Flathub, I get the following:
```
Required runtime for org.openmw.OpenMW/x86_64/stable (runtime/org.kde.Platform/x86_64/5.14) found in remote flathub
Do you want to install it? [Y/n]: 
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
```
The runtime might need to be updated if possible.

### PR DESCRIPTION
**Pull request by ananace**
Waiting for the official release to be done before merging

Fixes #12 #14 #16
Replaces #13

### CODE REVIEW

**Comment by cboxdoerfer** [comment]
@ananace, 0.47 was released today: https://openmw.org/2021/openmw-0-47-0-released/

**Comment by ananace** [comment]
Yep, and now that I'm back home as well it's time to press the big green button.

**Comment by Mershl** [comment]
Hi @ananace, thank you very much for preparing and bundling this release!

FYI: By default the flathub publish process includes a 3 hour release delay before a publish to flathub. This is done to give maintainers an option to pull pack a release last minute if they notice a bug or typo. https://github.com/flathub/flathub/wiki/App-Maintenance#automatic-publishing-delay

**Comment by cboxdoerfer** [comment]
The update is now available on flathub and it works wonderfully. Thanks!

**Pull request merged**
