### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by ananace** [comment]
I've been poking at this, but it's going to require some dependency changes, so I'm working on it locally - with the plans to push it to the beta branch once I get a proper build from it.

**Comment by AsciiWolf** [comment]
I think I had the same ffmpeg issue in one of my Flatpaks. I have solved it by updating the ffmpeg module and adding an upstream patch: https://github.com/flathub/org.sdrangel.SDRangel/blob/master/org.sdrangel.SDRangel.yaml#L131

**Comment by AsciiWolf** [comment]
@ananace I have added [this patch](https://github.com/flathub/org.sdrangel.SDRangel/blob/master/ffmpeg-fix-assembling.patch), let's see if it builds now. If not, it will also require ffmpeg version update. Anyway, I am closing this PR after the build in favor of your local beta build.

**Comment by AsciiWolf** [comment]
It looks like it did work. :-) But crashed on a mygui build.

Anyway, I am closing this PR. @ananace Feel free to add the ffmpeg patch to your local build and continue the work there.

**Comment by ananace** [comment]
Decided to give up on trying to figure out the remaining glitches I have in my local tests, they seem to be things that will be fixed with the next release - and they're not affecting gameplay as far as I can see, so a small version bump for MyGUI and your ffmpeg patch seems in order. (It's a lot cleaner than my own finagling with ffmpeg, that's for certain)

**Comment by AsciiWolf** [comment]
Could you prepare the update? I am quite busy with other work tasks at the moment and have already deleted the cloned Git repo with my changes. :-/

**Comment by ananace** [comment]
Already merged into beta, was planning on leaving it there for a few days - also quite busy with work, and then promote it to stable

**Pull request closed without merging**
